version: '3.8'
services:
  dnsmasq:
    restart: always
    build:
      context: .
      dockerfile: dockerfile_dnsmasq
    container_name: dnsmasq
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    volumes:
      # configファイル
      - ./conf/dnsmasq.conf:/etc/dnsmasq.conf
      - ./conf/dnsmasq-hosts:/etc/dnsmasq-hosts
      - ./conf/dnsmasq-resolv.conf:/etc/dnsmasq-resolv.conf
      # logファイル
      - dnsmasq:/var/log/dnsmasq/dnsmasq.log
volumes:
  dnsmasq:
    driver: local
