version: '3.8'
services:
  dnsmasq:
    restart: always
    build:
      context: .
      dockerfile: dockerfile_dnsmasq
    container_name: dnsmasq
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN  #必須
    volumes:
      # configファイル
      - ./conf/dnsmasq.conf:/etc/dnsmasq.conf
      # /etc/hostsを共用
      - /etc/hosts:/etc/hosts  
      # logファイル
      - dnsmasq:/var/log/dnsmasq
volumes:
  dnsmasq:
    driver: local
